name: Gamma Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

jobs:
  gamma-deploy:
    runs-on: ubuntu-latest
    environment:
      name: gamma
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy Gamma to Checkly
        run: npx checkly deploy --force --config=./checkly.gamma.config.ts
        env:
          CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
          CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
          PAGER_DUTY_ACCOUNT: ${{ secrets.PAGER_DUTY_ACCOUNT }}
          PAGER_DUTY_SERVICE_NAME: ${{ secrets.PAGER_DUTY_SERVICE_NAME }}
          PAGER_DUTY_SERVICE_KEY: ${{ secrets.PAGER_DUTY_SERVICE_KEY }}
          INSTANCE_ID: ${{ secrets.INSTANCE_ID }}
          SITE_URL: ${{ secrets.SITE_URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}